In [6]:
#This whole code notebook is an reproducation of book Grokking-Deep-Learning charpter 3
#Nerual Network 101
weight = 0.1
def neural_network(input,weight):
    predication = input * weight
    return predication
number_of_toes = [8.5,9.5,10,9]
input = number_of_toes[0]
pred = neural_network(input,weight)
print(pred)


0.8500000000000001


In [9]:
#Making a Prediction with Multiple Inputs
weights = [0.1,0.2,0]
toes = [8.5,9.5,9.9,9.0]
wlrec = [0.65,0.8,0.8,0.9]
nfans = [1.2,1.3,0.5,1.0]

def w_sum(a,b):
    assert(len(a)==len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

def neural_network(inputs,weights):
    predication = w_sum(inputs,weights)
    return predication

inputs = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(inputs,weights)

print(pred)

0.9800000000000001


In [1]:
#Numpy Code version of above code
import numpy as np
weights = np.array([0.1,0.2,0])
toes = np.array([8.5,9.5,9.9,9.0])
wlrec = np.array([0.65,0.8,0.8,0.9])
nfans = [1.2,1.3,0.5,1.0]

def neural_network(inputs,weights):
    predication = inputs.dot(weights)
    return predication

inputs = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(inputs,weights)
print(pred)

0.9800000000000001


In [2]:
#Making a Predication with Multiple Outpus
#Instead of predicting just
#whether the team won or lost,
#now we're also predicating whether
#they are happy/sad AND the percentage
#of the team that is hurt. We are only
#the current win/losss record
weights = [0.3,0.2,0.9]
wlrec = [0.65,0.8,0.8,0.9]
input = wlrec[0]

def ele_mul(number,vector):
    output = [0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

def neural_network(input,vector):
    predication = ele_mul(input,vector)
    return predication

pred = neural_network(input,weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


In [7]:
#Predicting with Multiple Inputs & Outputs
#This dataset is the current
#status at the beginning of
#each game for the first 4 games
#in a season

#toes = current number of toes
#wlrec = current games won (percent)
#nfans = fan count (in millons)

toes = [8.5,9.5,9.9,9.0]
wlrec = [0.65,0.8,0.8,0.9]
nfans = [1.2,1.3,0.5,1.0]

weights =[[0.1,0.1,-0.3,], #hurt?
          [0.1,0.2,0.0], #win?
          [0.0,1.3,0.1]]  #sad?
#Input corresponds to every entry
#for the first game of the season

input = [toes[0],wlrec[0],nfans[0]]

def w_sum(a,b):
    assert(len(a)==len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output
    
def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect,matrix[i])
    return output

def neural_network(input,weights):
    predication = vect_mat_mul(input,weights)
    return predication

pred = neural_network(input,weights)

print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


In [9]:
#Predicting on predictions
toes = [8.5,9.5,9.9,9.0]
wlrec = [0.65,0.8,0.8,0.9]
nfans = [1.2,1.3,0.5,1.0]

ih_wgt = [[0.1,0.2,-0.1],
          [-0.1,0.1,0.9],
          [0.1,0.4,0.1]]

hp_wgt = [[0.3,1.1,-0.3],
          [0.1,0.2,0.0],
          [0.0,1.3,0.1]]

weights = [ih_wgt,hp_wgt]

def w_sum(a,b):
    assert(len(a)==len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output
    
def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect,matrix[i])
    return output
    
def neural_network(input,weights):
    hid = vect_mat_mul(input,weights[0])
    pred = vect_mat_mul(hid,weights[1])
    return pred
    
input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)
print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [12]:
#Numpy version Predicting on predictions, output is differnt to offical
import numpy as np
toes = np.array([8.5,9.5,9.9,9.0])
wlrec = np.array([0.65,0.8,0.8,0.9])
nfans = np.array([1.2,1.3,0.5,1.0])

ih_wgt = np.array([[0.1,0.2,-0.1],
          [-0.1,0.1,0.9],
          [0.1,0.4,0.1]])

hp_wgt = np.array([[0.3,1.1,-0.3],
          [0.1,0.2,0.0],
          [0.0,1.3,0.1]])

weights = [ih_wgt,hp_wgt]

    
def neural_network(input,weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred
    
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
print(pred)

[ 0.496  1.256 -0.286]


In [14]:
# A Quick Primer on NumPy
import numpy as np

a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # another vector
c = np.array([[0,1,2,3],
             [4,5,6,7]]) # a matrix

d = np.zeros((2,4)) # (2 * 4 matrix of zeros)
e = np.random.rand(2,5) # random 2*5
# matrix with all numbers between 0 and 1

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.59213824 0.53975179 0.89331469 0.12613366 0.33279003]
 [0.37452519 0.54038541 0.46576193 0.29621144 0.9974632 ]]


In [15]:
import numpy as np

a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # another vector
c = np.array([[0,1,2,3],
             [4,5,6,7]]) # a matrix

d = np.zeros((2,4)) # (2 * 4 matrix of zeros)
e = np.random.rand(2,5) # random 2*5
# matrix with all numbers between 0 and 1

print(a * 0.1) #multiplies every number in vector "a" by 0.1
print(c * 0.1)  #multiplies every number in matrix "c" by 0.1
print(a * b) #multiplies elementwise between a and b (columns paired up)
print(a * b * 0.2) #elementwise multiplication then multiplied by 0.2
print(a * c) #since c has the same number of columns as a, this performs 
#elementwise mutiplication on every row of the matrix "c"
print(a * e) #since a and e don't have the same number of columns, this 
#throws a "Value Error: operands could not be broadcast together with.."


[0.  0.1 0.2 0.3]
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [16]:
import numpy as np
a = np.zeros((1,4)) # vector of length 4
b = np.zeros((4,3)) # matrix with 4 rows & 3 columns

c = a.dot(b)

print(c.shape)

(1, 3)


In [18]:
import numpy as np

a = np.zeros((2,4)) # matrix with 2 rows and 4 columns
b = np.zeros((4,3)) # matrix with 4 rows & 3 columns

c = a.dot(b)
print(c.shape) #output (2,3)

e = np.zeros((2,1)) # matrix with 2 rows and 1 columns
f = np.zeros((1,3)) # matrix with 1 row & 3 columns

g = e.dot(f)
print(g.shape) #output (2,3)

h = np.zeros((5,4)).T # matrix with 4 rows and 5 columns
i = np.zeros((5,6)) # matrix with 5 rows & 6 columns
j = h.dot(i)

print(j.shape) # throw an error

(2, 3)
(2, 3)
(4, 6)


In [19]:
import numpy as np
h = np.zeros((5,4)) # matrix with 5 rows and 4 columns
i = np.zeros((5,6)) # matrix with 5 rows & 6 columns
j = h.dot(i)

print(j.shape) # throw an error

ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)